package models

import play.api.libs.json.JsValue
import java.time.Instant

/**
 * Represents a system-level notification event generated by various subsystems
 * such as maintenance, inventory, or allocation workflows. These events are
 * typically processed by a notification dispatcher or message broker for
 * publishing emails, alerts, or system messages.
 *
 * @param eventId       Unique identifier of the notification event.
 * @param eventType     Type of event that triggered the notification.
 *                      Examples include:
 *                      - "OVERDUE_REMINDER"
 *                      - "MAINTENANCE_ALERT"
 *                      - "INVENTORY_UPDATE"
 *
 * @param allocationId  Optional ID of an equipment allocation associated with the event.
 *                      Used for allocation-related reminders or notifications.
 *
 * @param ticketId      Optional ID of a maintenance or support ticket linked to the event.
 *
 * @param payload       Raw JSON payload containing event-specific details.
 *                      This can include contextual metadata required by
 *                      downstream processors (email templates, notification services, etc.).
 *
 * @param status        Current processing status of the event.
 *                      Possible values:
 *                      - "PENDING": Queued and waiting to be published
 *                      - "PUBLISHED": Successfully dispatched
 *                      - "FAILED": Processing failed; may be retried
 *
 * @param createdAt     Timestamp when the event was generated.
 *
 * @param publishedAt   Optional timestamp indicating when the event was successfully
 *                      published or dispatched to external systems.
 *
 * @param lastError     Optional error message captured when a publish attempt fails.
 *                      Useful for debugging and retry logic.
 */
case class NotificationEvent(
                              eventId: Long,
                              eventType: String,
                              allocationId: Option[Int],
                              ticketId: Option[Int],
                              payload: JsValue,
                              status: String,
                              createdAt: Instant,
                              publishedAt: Option[Instant],
                              lastError: Option[String]
                            )
