package models

import java.time.Instant
import play.api.libs.json.JsValue

/**
 * Represents an event generated by the system for asynchronous processing
 * (e.g., sending notifications, publishing messages to Kafka, triggering workflows).
 *
 * Each NotificationEvent captures:
 *  - The type of event (maintenance-related, inventory changes, overdue reminders)
 *  - Links to related objects (allocation, ticket)
 *  - Raw JSON payload to be consumed by external systems
 *  - Publishing metadata (status, timestamps, error logs)
 *
 * These events are typically created by controllers/services and processed by
 * background workers or Kafka consumers for notifications, alerts, or system updates.
 *
 * @param eventId Unique identifier for the event
 *
 * @param eventType Logical category of the event, such as:
 *                  - `"OVERDUE_REMINDER"`     → equipment allocation is overdue
 *                  - `"MAINTENANCE_ALERT"`    → damaged return triggers a maintenance alert
 *                  - `"INVENTORY"`            → inventory create/update/delete event
 *                  - `"MAINTENANCE"`          → ticket created/updated/assigned
 *
 * @param allocationId Optional equipment allocation associated with this event
 * @param ticketId Optional maintenance ticket associated with this event
 *
 * @param payload Raw JSON payload containing event-specific details
 *
 * @param status Current processing status:
 *               - `"PENDING"`    → event is created but not yet published
 *               - `"PUBLISHED"`  → successfully published to Kafka / worker
 *               - `"FAILED"`     → publishing failed; retry may be needed
 *
 * @param createdAt Timestamp when the event was created
 * @param publishedAt Optional timestamp when the event was successfully published
 * @param lastError Optional error message from the last failed publishing attempt
 */
case class NotificationEvent(
                              eventId: Long,
                              eventType: String,           // OVERDUE_REMINDER, MAINTENANCE_ALERT, INVENTORY, MAINTENANCE
                              allocationId: Option[Int],
                              ticketId: Option[Int],
                              payload: JsValue,            // raw JSON payload for the message

                              status: String,              // PENDING, PUBLISHED, FAILED
                              createdAt: Instant,
                              publishedAt: Option[Instant],
                              lastError: Option[String]
                            )
